/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var r=Object.defineProperty;var i=Object.getOwnPropertyDescriptor;var n=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var d=(o,e)=>{for(var l in e)r(o,l,{get:e[l],enumerable:!0})},u=(o,e,l,p)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of n(e))!c.call(o,s)&&s!==l&&r(o,s,{get:()=>e[s],enumerable:!(p=i(e,s))||p.enumerable});return o};var A=o=>u(r({},"__esModule",{value:!0}),o);var g={};d(g,{default:()=>t});module.exports=A(g);var a=require("obsidian"),t=class extends a.Plugin{async onload(){console.log("Close 'All properties' plugin loaded."),this.app.workspace.onLayoutReady(()=>{this.checkAndCloseAllProperties()})}onunload(){console.log("Close 'All properties' plugin  unloaded")}async checkAndCloseAllProperties(){setTimeout(()=>{this.app.workspace.iterateAllLeaves(e=>{if(e.getViewState().type==="all-properties")return e.detach(),console.log("Closed 'All Properties' tab."),!0})},500)}};
